@startuml
    skinparam backgroundcolor transparent
    set namespaceSeparator none
    hide circle
    hide empty fields
    hide empty methods

    oop.collections --> java.lang
    oop.collections --> java.util

    ' Package links
    class "oop.collections" [[oop/collections/package-summary.html]] {
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
