@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Main\n<size:10>oop.collections" as oop.collections.Main [[Main.html]] {
        {static} +HEART_TRANSPLANT: Surgery
        {static} +LUNG_X_RAY: Surgery
        {static} +MAKE_PLASTER_CAST: Surgery
        {static} +CHANGE_PLASTER: Surgery
        {static} +ROUTINE_HEALTH_CHECK: Surgery
        {static} +TICK_BORNE_VACCINATION: Surgery
        {static} +main(String[]): void
        {static} -displaySurgeries(List<Surgery>): void
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
