@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Surgery\n<size:10>oop.collections" as oop.collections.Surgery [[Surgery.html]] {
        -id: int
        -title: String
        -severity: int
        -duration: int
        -needsDoctor: boolean
        +Surgery(int, String, int, int, boolean)
        +getId(): int
        +getTitle(): String
        +getSeverity(): int
        +getDuration(): int
        +getNeedsDoctor(): boolean
        +compareTo(Surgery): int
    }

    interface "<size:14>Comparable\n<size:10>java.lang" as java.lang.Comparable<Surgery> {
        {abstract} +compareTo(Surgery): int
    }

    java.lang.Comparable <|.. oop.collections.Surgery

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
