@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>SurgeryPlanner\n<size:10>oop.collections" as oop.collections.SurgeryPlanner [[SurgeryPlanner.html]] {
        -surgeries: List<Surgery>
        +registerSurgery(Surgery): void
        +getAllRegisteredSurgeries(): List<Surgery>
        +unregisterSurgery(Surgery): void
        +getSurgeriesOrderedBySeverity(): List<Surgery>
        +getSurgeriesNeedingDoctor(): List<Surgery>
        +getSurgeriesLongerThan(int): List<Surgery>
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
